site_name: bioforklift
site_url: https://theiagen.github.io/bioforklift/
repo_url: https://github.com/theiagen/bioforklift/
repo_name: theiagen/bioforklift
site_description: A Python package for moving data between Google Cloud Platform services.

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tooltips
    - content.footnote.tooltips  
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 3
  - footnotes

plugins:
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/theiagen/bioforklift/

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Core Concepts: core_concepts.md
  - Interfaces:
    - Terra: interfaces/terra_interface.md
    - BigQuery: interfaces/bigquery_interface.md
    - Terra2BQ: interfaces/terra2bq_interface.md
  - Examples:
    - Backfilling Metadata: examples/backfilling_metadata.md
    - H5N1: examples/h5n1_example.md
    - CalTB-Net: examples/tb_example.md
  - Alerting:
    - Sentry: interfaces/sentry_setup.md
    